### PR TITLE
ability to include/exclude relation data in payload (fixes #63)

### LINKED ISSUE #63: options for serializing relationships
Currently, we have a method to completely disable the serialization AND inclusion of relationships via the `relations` property. However, this option only affects whether or not relations are `included` in the payload; it's either all or nothing. We have no public API for serialization of the relationships, but not including the actual related resources as part of the payload. This can be done by passing `included: false` to the serializer directly, but it needs to be passed as a property of the relationship itself. Currently, this doesn't work properly because we pass all `serializerOptions` at the root level.

This is both a bug and an opportunity to define a public API as to whether or not relationships are included as part of the payload.

My suggestion for the API:

* `relations` - this property would remain the same and would strictly affect whether or not relations are serialized as part of the payload, either as linkage or included.
* `includeRelations` - this property affects whether or not the relations are included as a compound document (embedded).

Scenarios:

**Relationships enabled and included**
* `relations: true`
* `includeRelations: true`

```js
{
  "included": [
    {
      "type": "pet",
      "id": "60",
      "attributes": {
        "name": "Toney"
    }
  ],
  "data": {
    "type": "customer",
    "id": "37",
    "attributes": {
      "firstName": "Peter",
      "lastName": "Fritsch"
    },
    "relationships": {
      "pets": {
        "data": [
          {
            "type": "pet",
            "id": "60"
          }
        ]
      }
    }
  }
}
```

**Relationships enabled and NOT included**
* `relations: true`
* `includeRelations: false`

```js
{
  "data": {
    "type": "customer",
    "id": "37",
    "attributes": {
      "firstName": "Peter",
      "lastName": "Fritsch"
    },
    "relationships": {
      "pets": {
        "data": [
          {
            "type": "pet",
            "id": "60"
          }
        ]
      }
    }
  }
}
```

**Relationships disabled**
* `relations: false`
* `includeRelations: false` (has no effect)

```js
{
  "data": {
    "type": "customer",
    "id": "37",
    "attributes": {
      "firstName": "Peter",
      "lastName": "Fritsch"
    }
  }
}
```

@chamini2 @ShadowManu thoughts? I'm going to start working on this now as it's something I need to implement, but open to changes.

### PR DESCRIPTION
**Pull request by jamesdixon**
This PR fixes #63 by allowing an `included` attribute to be specified as part of the `relations` option. Previously, the `relations` option was either a boolean or an array of strings. This has now been changed to either a boolean or an object containing options that determine how a relationship is processed.

The array of relation names has now been moved into a `fields` property. Example:

```js
relations: {
  fields: ['rel1', 'rel2']
}
```

The new syntax also allows for an `included` option to determine whether the relation data is included as a compound document, which has been the default thus far. Setting `included: false` will not include the actual relation data in the payload.

Scenarios:

```js
relations : true // all in, to maintain the current behaviour
relations : false // nothing
relations : { included: true } // relation data included in payload
relations : { included: false } // relations defined, but data not included in payload
```

### CODE REVIEW

**Comment by jamesdixon** [comment]
@chamini2 @ShadowManu would love your feedback on this.

**Comment by jamesdixon** [comment]
Note that I haven't updated the README yet, but will do so after getting your feedback.

File: src/relations.d.ts [hunk 1]
```diff
@@ -14,3 +14,8 @@ export type RelationTypeFunction = (attribute: string) => string;
  * The relationTypes option can be a function or an object
  */
 export type RelationTypeOpt = RelationTypeMap | RelationTypeFunction;
+
+export interface RelationOpts {
```
Comment (chamini2) [inline src/relations.d.ts]: What about moving this `boolean | ...` to the `src/relations.d.ts` file

Maybe like:
```
export type RelationOpt = boolean | RelationDetails
interface RelationDetails {
  included?: boolean,
  fields?: string[]
}
```

File: src/bookshelf/index.ts [hunk 2]
```diff
@@ -30,7 +30,7 @@ export default class Bookshelf implements Mapper {
     let linkOpts: LinkOpts = { baseUrl: this.baseUrl, type, pag: bookOpts.pagination };
 
     // Set default values for the options
-    bookOpts = assign({relations: true, enableLinks: true}, bookOpts);
+    bookOpts = assign({relations: { included: true }, enableLinks: true}, bookOpts);
```
Comment (chamini2) [inline src/bookshelf/index.ts]: We could change this to

```
defaultsDeep(bookOpts, {relations: { include: true }, enableLinks: true})
```
So when only `relations : {fields : ['a', 'b']}` is passed, it completes it with `relations: {fields: ['a','b'], include: true}`

Comment (chamini2) [inline src/bookshelf/index.ts]: `defaultsDeep` is in-place, so no need to assign it back to `bookOpts`

File: src/bookshelf/utils.ts [hunk 3]
```diff
@@ -66,6 +68,11 @@ function processSample(info: Information, sample: Model): SerialOpts {
       relTemplate.includedLinks = includedLinks(relLinkOpts);
     }
 
+    // Include links as compound document
+    if (!included) {
```
Comment (chamini2) [inline src/bookshelf/utils.ts]: what about removing the whole `if ...` for `relTemplate.included = included`

File: src/bookshelf/utils.ts [hunk 4]
```diff
@@ -123,10 +130,11 @@ function getAttrsList(data: Model): any {
  */
 function relationAllowed(bookOpts: BookOpts, relName: string): boolean {
   let { relations }: BookOpts = bookOpts;
+  let { fields }: RelationOpts = relations;
 
   return relations === true ||
-    (typeCheck('[String]', relations) &&
-      (relations as string[]).some((rel: string) => rel === relName));
+         relations instanceof Object ||
+         (fields instanceof Object && (fields as string[]).some((rel: string) => rel === relName));
```
Comment (chamini2) [inline src/bookshelf/utils.ts]: maybe test for `fields instanceof Array` instead? (I don't know if you would still need the casting `(fields as string[])`

Comment (jamesdixon) [inline src/bookshelf/utils.ts]: Thanks for catching that!

File: src/bookshelf/index.ts (hunk 2 above)
Comment (chamini2) [inline src/bookshelf/index.ts]: Also, doing this may make the `included?` in `RelationOpts` not be optional, right?

File: src/relations.d.ts (hunk 1 above)
Comment (jamesdixon) [inline src/relations.d.ts]: Fine with me!

Comment (jamesdixon) [inline src/relations.d.ts]: I just changed this and it broke a bunch of things. That said, in the interest of time, I'm just going to leave this as-is. Seems more of a cosmetic change than anything, no?

**Comment by jamesdixon** [comment]
@chamini2 thanks for the thorough review. I just pushed a few fixes from above.

**Comment by jamesdixon** [comment]
If you're good with the changes, LGTM 👍

File: src/relations.d.ts (hunk 1 above)
Comment (chamini2) [inline src/relations.d.ts]: It would be cosmetic, you're right.

**Comment by jamesdixon** [comment]
1.0.0-beta.4 is live
