### PR TITLE
don't add unneeded pagination links (fixes #40)

### LINKED ISSUE #40: toJSON is recursive on relations, template generation is not.
Currently the template builder does not support withRelated properties which go deeper then one relation.

`this.that` works, but `this.that.andthat` does not.

It seems to me https://github.com/scoutforpets/jsonapi-mapper/blob/master/src/bookshelf/mapper.ts#L122-L138 should become recursive, correct me if I'm wrong. I can have a swing at it and make a PR if you agree this is what needs to happen.

### PR DESCRIPTION
**Pull request by jamesdixon**

### CODE REVIEW

**Comment by chamini2** [comment]
I find a little strange that the `offset` is larger than `total` in the tests, or am I missing something?

Also, maybe you could omit pagination links for `prev` and `first` when `offset = 0`, and the same for `next` and `last` when already at the end of the *pages*. But I don't know if that would break any standard?

File: spec/bookshelf-spec.ts [hunk 1]
```diff
@@ -616,6 +616,48 @@ describe('Bookshelf links', () => {
     expect(_.matches(expected)(result)).toBe(true);
   });
 
+  it('should not add pagination links if collection is empty', () => {
+    let limit: number = 10;
+    let offset: number = 40;
```
Comment (chamini2) [inline spec/bookshelf-spec.ts]: `{limit: 10, offset: 0, total: 5}`?

Comment (jamesdixon) [inline spec/bookshelf-spec.ts]: It works because `total` is equal to `limit`. Am I missing something?

Comment (chamini2) [inline spec/bookshelf-spec.ts]: It just seems weird that `offset > total`, but you are right that it should work nonetheless!

Comment (jamesdixon) [inline spec/bookshelf-spec.ts]: Sorry, I was looking at the wrong test. In this case, I'm checking to see if the collection is empty (`total = 0`), so the `offset` and `limit` are irrelevant.

File: spec/bookshelf-spec.ts [hunk 2]
```diff
@@ -616,6 +616,48 @@ describe('Bookshelf links', () => {
...
+    });
+
+    expect(result.links).toBeDefined();
+    expect(Object.keys(result.links)).not.toContain(['first', 'prev', 'next', 'last']);
+  });
+
+  it('should not add pagination links if total <= limit', () => {
+    let limit: number = 10;
+    let offset: number = 0;
+    let total: number = 10;
```
Comment (jamesdixon) [inline spec/bookshelf-spec.ts]: This is the line I was referencing and had changed.

**Comment by chamini2** [comment]
And about my second comment, what do you think?

> Also, maybe you could omit pagination links for prev and first when offset = 0, and the same for next and last when already at the end of the pages. But I don't know if that would break any standard?

**Comment by jamesdixon** [comment]
Yes, I think that makes sense and seems in accordance with the spec: http://jsonapi.org/format/#fetching-pagination

**Comment by jamesdixon** [comment]
Another question for you:

Bookshelf now has paging built-in through the `bookshelf-page` plugin: http://bookshelfjs.org/#Model-instance-fetchPage

The paging params available are named differently than what we currently have. Thinking we should add support for parsing those params automatically. We could either deprecate the others or keep support.

**Comment by jamesdixon** [comment]
@chamini2 added code to omit specific links based on params and also added support for the `rowCount` parameter that's passed back when using `Bookshelf#Model.fetchPage()` -- backwards compatible. Let me know your thoughts

**Comment by chamini2** [comment]
The new specs seem to have a problem, I'll add comments on the lines.

File: spec/bookshelf-spec.ts [hunk 3]
```diff
@@ -616,6 +616,133 @@ describe('Bookshelf links', () => {
...
+    let result: any = mapper.map(collection, 'models', {
+      pagination: {
+        limit: limit,
+        offset: offset,
+        total: total
+      }
+    });
+
+    expect(result.links).toBeDefined();
+    expect(Object.keys(result.links)).not.toContain(['next', 'last']);
```
Comment (chamini2) [inline spec/bookshelf-spec.ts]: It should omit `first` and `prev` not `next` and `last`. But it is passing because `['next', 'last']` is not an element of `['links', 'next', 'last']`; should be passing the arguments outside of an array (i.e. `toContain('next', 'last')`)

File: spec/bookshelf-spec.ts [hunk 4]
```diff
@@ -616,6 +616,133 @@ describe('Bookshelf links', () => {
...
+    let result: any = mapper.map(collection, 'models', {
+      pagination: {
+        limit: limit,
+        offset: offset,
+        total: total
+      }
+    });
+
+    expect(result.links).toBeDefined();
+    expect(Object.keys(result.links)).not.toContain(['first', 'prev', 'next', 'last']);
```
Comment (chamini2) [inline spec/bookshelf-spec.ts]: Same problem here with passing an array to `toContain`, drop the `[]`

File: spec/bookshelf-spec.ts [hunk 5]
```diff
@@ -616,6 +616,133 @@ describe('Bookshelf links', () => {
...
```
Comment (chamini2) [inline spec/bookshelf-spec.ts]: Same problem here with passing an array to `toContain`, drop the `[]`

File: spec/bookshelf-spec.ts [hunk 6]
```diff
@@ -616,6 +616,133 @@ describe('Bookshelf links', () => {
...
+    let result: any = mapper.map(collection, 'models', {
+      pagination: {
+        limit: limit,
+        offset: offset,
+        total: total
+      }
+    });
+
+    expect(result.links).toBeDefined();
+    expect(Object.keys(result.links)).not.toContain(['first', 'prev']);
```
Comment (chamini2) [inline spec/bookshelf-spec.ts]: Same problem here with passing an array to `toContain`, drop the `[]`; and should be testing with `(next, last)`.

File: spec/bookshelf-spec.ts (hunk 3 above)
Comment (chamini2) [inline spec/bookshelf-spec.ts]: Sorry, I was wrong, it should be a new call for each elemet:
```
expect(Object.keys(result.links)).not.toContain('next');
expect(Object.keys(result.links)).not.toContain('last');
```

File: spec/bookshelf-spec.ts [hunk 7]
```diff
@@ -616,6 +616,133 @@ describe('Bookshelf links', () => {
...
+
+    let elements: Model[] = _.range(10).map((num: number) => {
+      return bookshelf.Model.forge<any>({id: num, attr: 'value' + num});
+    });
+
+    let collection: Collection = bookshelf.Collection.forge<any>(elements);
+
+    let result: any = mapper.map(collection, 'models');
+
+    expect(result.links).not.toContain(['first', 'prev', 'next', 'last']);
```
Comment (chamini2) [inline spec/bookshelf-spec.ts]: Same problem here with passing an array to `toContain`, pass each argument in a new call.

Comment (jamesdixon) [inline spec/bookshelf-spec.ts]: @chamini2 you're right. Sorry, I believe I had misread the Jasmine documentation and thought I could pass an array of values. I'll fix this.

Comment (jamesdixon) [inline spec/bookshelf-spec.ts]: @chamini2 fixed 👍

**Comment by jamesdixon** [comment]
@chamini2 can you verify my changes?

**Comment by chamini2** [comment]
@jamesdixon, it looks good!
